/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/over.ts" />
/// <reference path="../scenes/node1.ts" />
/// <reference path="../scenes/node2.ts" />
/// <reference path="../scenes/node3.ts" />
/// <reference path="../scenes/node4.ts" />
/// <reference path="../scenes/node5.ts" />
/// <reference path="../scenes/node6.ts" />
/// <reference path="../scenes/node7.ts" />
/// <reference path="../scenes/outcome-killed.ts" />
/// <reference path="../scenes/outcome-smashed.ts" />
/// <reference path="../scenes/outcome-exit.ts" />
/// <reference path="../scenes/menu.ts" />
//# sourceMappingURL=_reference.js.map